version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      target: build
      args:
        TEMPLATE_ID: "080f31ca-972e-4ddb-b228-5ea862d82125"
        COMPANY_ID: "410"  # Company ID set to 410
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start

  # Production service
  prod:
    build:
      context: .
      args:
        TEMPLATE_ID: "080f31ca-972e-4ddb-b228-5ea862d82125"
        COMPANY_ID: "410"  # Company ID set to 410
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production 